version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dotnetapp_sql
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"   # minimum 8 char, must include uppercase/lowercase/digit/symbol
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"                        # exposes to host, so you can connect from SSMS
    volumes:
      - sql_data:/var/opt/mssql            # persistent data storage
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Src/__SolutionName__.Api/Dockerfile
    container_name: dotnetapp_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Use SQL Server service name from compose (sqlserver)
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=__SolutionName__Db;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge